//
// Generated file, do not edit! Created by opp_msgtool 6.0 from veins_inet/VeinsInetSampleMessage.msg.
//

#ifndef __VEINSINETSAMPLEMESSAGE_M_H
#define __VEINSINETSAMPLEMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class VeinsInetSampleMessage;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>veins_inet/VeinsInetSampleMessage.msg:31</tt> by opp_msgtool.
 * <pre>
 * class VeinsInetSampleMessage extends inet::FieldsChunk
 * {
 *     string roadId;
 *     double speed;
 *     double position;
 *     bool emergencyBrake;
 * }
 * </pre>
 */
class VeinsInetSampleMessage : public ::inet::FieldsChunk
{
  protected:
    omnetpp::opp_string roadId;
    double speed = 0;
    double position = 0;
    bool emergencyBrake = false;

  private:
    void copy(const VeinsInetSampleMessage& other);

  protected:
    bool operator==(const VeinsInetSampleMessage&) = delete;

  public:
    VeinsInetSampleMessage();
    VeinsInetSampleMessage(const VeinsInetSampleMessage& other);
    virtual ~VeinsInetSampleMessage();
    VeinsInetSampleMessage& operator=(const VeinsInetSampleMessage& other);
    virtual VeinsInetSampleMessage *dup() const override {return new VeinsInetSampleMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getRoadId() const;
    virtual void setRoadId(const char * roadId);

    virtual double getSpeed() const;
    virtual void setSpeed(double speed);

    virtual double getPosition() const;
    virtual void setPosition(double position);

    virtual bool getEmergencyBrake() const;
    virtual void setEmergencyBrake(bool emergencyBrake);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const VeinsInetSampleMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, VeinsInetSampleMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline VeinsInetSampleMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<VeinsInetSampleMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINSINETSAMPLEMESSAGE_M_H

